language: csharp
mono: none
dotnet: 2.2.105
dist: xenial
install:
- dotnet restore ./src/RestfulProfiles.sln
script:
- dotnet build ./src/RestfulProfiles.sln
- dotnet test ./src/ProfileApi.Tests/ProfileApi.Tests.csproj